# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 843d5fc78d7ff4c32280b71a0c07ede8aa3800588740b4877e61a481b80ee86a91d17e4dd6172fa1426b50b130663a89d840a3075609ef5566b3eb060ef7e342

test:
  secret_key_base: 6c812f5c4d8f25967a435903d81c5f82901205fe3a3e4cada23db785a59c361d5fccbdfe6b8d74890edae79de4aa3f2a257e6658604695456abf1786f4fb51b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
